const state={bank:[],quiz:[],answers:{},index:0};
const $=s=>document.querySelector(s);
const screens={home:$('#home'),quiz:$('#quiz'),result:$('#result')};
function show(name){Object.values(screens).forEach(x=>x.classList.remove('active'));screens[name].classList.add('active');window.scrollTo(0,0)}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function start(){state.quiz=shuffle(state.bank).slice(0,25);state.answers={};state.index=0;show('quiz');renderQuestion()}
function renderQuestion(){const q=state.quiz[state.index];$('#qNo').textContent=state.index+1;$('#progressBar').style.width=((state.index+1)/25*100)+'%';$('#questionImage').src='assets/'+q.questionImage;const box=$('#options');box.innerHTML='';['A','B','C','D'].forEach(k=>{const b=document.createElement('button');b.className='option'+(state.answers[q.id]===k?' selected':'');b.innerHTML=`<span class="option-key">${k}</span>選擇 ${k}`;b.onclick=()=>{state.answers[q.id]=k;renderQuestion()};box.appendChild(b)});$('#prevBtn').disabled=state.index===0;$('#prevBtn').style.opacity=state.index===0?.45:1;$('#nextBtn').textContent=state.index===24?'交卷':'下一題'}
function next(){if(!state.answers[state.quiz[state.index].id]){alert('請先選擇答案。');return}if(state.index<24){state.index++;renderQuestion()}else submit()}
function prev(){if(state.index>0){state.index--;renderQuestion()}}
function submit(){const correct=state.quiz.filter(q=>state.answers[q.id]===q.answer).length;const wrong=25-correct;$('#score').textContent=correct*4;$('#correctCount').textContent=correct;$('#wrongCount').textContent=wrong;$('#accuracy').textContent=Math.round(correct/25*100)+'%';$('#wrongSummary').textContent=`共 ${wrong} 題錯題`;const list=$('#wrongList');list.innerHTML='';state.quiz.forEach((q,i)=>{if(state.answers[q.id]===q.answer)return;const item=document.createElement('div');item.className='wrong-item';const exp=q.explanationImage?`<div class="explanation"><div class="explanation-label">原 PDF 詳解</div><img src="assets/${q.explanationImage}" alt="詳解"></div>`:`<div class="explanation no-exp">這一題沒有詳解。</div>`;item.innerHTML=`<div class="wrong-title">第 ${i+1} 題　你的答案：${state.answers[q.id]||'未作答'}　｜　正確答案：${q.answer}</div><img src="assets/${q.questionImage}" alt="錯題"><div class="answer-line">本題 4 分。</div>${exp}`;list.appendChild(item)});show('result')}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(!a)return;const act=a.dataset.action;if(act==='start')start();if(act==='home')show('home');if(act==='quit')show('home')});$('#nextBtn').onclick=next;$('#prevBtn').onclick=prev;fetch('assets/questions.json').then(r=>r.json()).then(data=>{state.bank=data.filter(q=>q.answer);$('#bankCount').textContent=state.bank.length}).catch(()=>{$('#bankCount').textContent='載入失敗'});
